# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: autodoc
        name: document
        entry: bash -c 'python3 autodocs.py; sleep 0.1; git add -u' --
        language: system
        verbose: true
