# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# -   repo: https://github.com/starwort/computer-science
#     rev: 5f6304101e4c6b57ee677710364bdc16b387bdbc
#     hooks:
#     -   id: autodoc
