# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: autodoc
        name: document
        entry: bash -c './run_autodoc.py 2>log/autodocs_run_$RANDOM.log; sleep 0.5' --
        language: system
        verbose: false
        always_run: true
