filetype_to_url = {
    "html": "https://img.icons8.com/windows/512/bb86fc/regular-document.png",
    "htm": "https://img.icons8.com/windows/512/bb86fc/regular-document.png",
    "md": "https://img.icons8.com/windows/512/bb86fc/regular-document.png",
    "c": "https://img.icons8.com/windows/512/bb86fc/c.png",
    "cs": "https://img.icons8.com/windows/512/bb86fc/cs.png",
    "json": "https://img.icons8.com/windows/512/bb86fc/placeholder-thumbnail-json-1.png",
    "css": "https://img.icons8.com/windows/512/bb86fc/css.png",
    "scss": "https://img.icons8.com/windows/512/bb86fc/css.png",
    "js": "https://img.icons8.com/windows/512/bb86fc/js.png",
    "py": "https://img.icons8.com/windows/512/bb86fc/py.png",
    "dll": "https://img.icons8.com/windows/512/bb86fc/dll.png",
    "csv": "https://img.icons8.com/windows/512/bb86fc/csv.png",
    "exe": "https://img.icons8.com/windows/512/bb86fc/exe.png",
    "jpeg": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "jpg": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "png": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "tif": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "tiff": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "jfif": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "exif": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "bmp": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "pcx": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "pbm": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "gif": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "ppm": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "pgm": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "webp": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "ico": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "svg": "https://img.icons8.com/windows/512/bb86fc/image-document.png",
    "txt": "https://img.icons8.com/windows/512/bb86fc/document.png",
    "splw": "https://starwort.github.io/computer-science/icon-splw.png",
    "lmc": "https://starwort.github.io/computer-science/icon-lmc.png",
    "ocrpsc": "https://img.icons8.com/windows/512/bb86fc/code-file.png",
    "psc": "https://img.icons8.com/windows/512/bb86fc/code-file.png",
    "": "https://img.icons8.com/windows/512/bb86fc/binary-file.png",
    "clang-format": "https://img.icons8.com/windows/512/bb86fc/file-configuration.png",
    "gitignore": "https://img.icons8.com/windows/512/bb86fc/file-configuration.png",
    "licence": "https://img.icons8.com/windows/512/bb86fc/policy-document.png",
    "yaml": "https://img.icons8.com/windows/512/bb86fc/code-file.png",
    "yml": "https://img.icons8.com/windows/512/bb86fc/code-file.png",
    "folder": "https://starwort.github.io/computer-science/icon-folder.png",
}
missing_file = "https://img.icons8.com/windows/512/bb86fc/important-file.png"

